const vocabList = [
  { vocab: "Compel", result: "บังคับ (v.)" },
  { vocab: "Drastic", result: "รุนแรง (adj.)" },
  { vocab: "Accomplish", result: "ทำสำเร็จ (v.)" },
  { vocab: "Impartial", result: "เป็นกลาง (adj.)" },
  { vocab: "Acknowledge", result: "ยอมรับ (v.)" },
  { vocab: "Concise", result: "กระชับ (adj.)" },
  { vocab: "Wordy", result: "ใช้คำฟุ่มเฟือย (adj.)" },
  { vocab: "Foresee", result: "คาดการณ์ (v.)" },
  { vocab: "Fortify", result: "เสริมสร้าง (v.)" },
  { vocab: "Conduct", result: "จัดการ (v.)" },
  { vocab: "Anecdote", result: "เกร็ดเล็กเกร็ดน้อย (n.)" },
  { vocab: "Refuge", result: "ที่หลบภัย (n.)" },
  { vocab: "Candid", result: "ตรงไปตรงมา (adj.)" },
  { vocab: "Abrupt", result: "ทันทีทันใด (adj.)" },
  { vocab: "Morale", result: "ขวัญกำลังใจ (n.)" },
  { vocab: "Spectacular", result: "น่าตื่นตาตื่นใจ (adj.)" },
  { vocab: "Striking", result: "โดดเด่น (adj.)" },
  { vocab: "Appealing", result: "ดึงดูดใจ (adj.)" },
  { vocab: "Illuminate", result: "ให้แสงสว่าง (v.)" },
  { vocab: "Provoke", result: "ยั่วยุ (v.)" },
  { vocab: "Desire", result: "ความปรารถนา (n.)" },
  { vocab: "Menace", result: "ภัยคุกคาม (n.)" },
  { vocab: "Comply", result: "ปฏิบัติตาม (v.)" },
  { vocab: "Endorse", result: "รับรอง (v.)" },
  { vocab: "Interfere", result: "แทรกแซง (v.)" },
  { vocab: "Remedy", result: "การเยียวยา (n.)" },
  { vocab: "Novice", result: "มือใหม่ (n.)" },
  { vocab: "Imminent", result: "ใกล้เข้ามา (adj.)" },
  { vocab: "Profound", result: "ลึกซึ้ง (adj.)" },
  { vocab: "Condemn", result: "ประณาม (v.)" },
  { vocab: "Compliment", result: "คำชม (n.)" },
  { vocab: "Surpass", result: "เหนือกว่า (v.)" },
  { vocab: "Tentative", result: "ไม่แน่นอน (adj.)" },
  { vocab: "Prudent", result: "รอบคอบ (adj.)" },
  { vocab: "Modest", result: "ถ่อมตัว (adj.)" },
  { vocab: "Prosperous", result: "มั่งคั่ง (adj.)" },
  { vocab: "Arrogant", result: "หยิ่งยโส (adj.)" },
  { vocab: "Humane", result: "มีมนุษยธรรม (adj.)" },
  { vocab: "Reminisce", result: "รำลึกถึง (v.)" },
  { vocab: "Gather", result: "รวบรวม (v.)" },
  { vocab: "Legitimate", result: "ถูกต้องตามกฎหมาย (adj.)" },
  { vocab: "Naive", result: "ไร้เดียงสา (adj.)" },
  { vocab: "Apathy", result: "ความเฉยเมย (n.)" },
  { vocab: "Compassion", result: "ความเห็นอกเห็นใจ (n.)" },
  { vocab: "Elegant", result: "สง่างาม (adj.)" },
  { vocab: "Devise", result: "วางแผน (v.)" },
  { vocab: "Convey", result: "ถ่ายทอด (v.)" },
  { vocab: "Relevant", result: "เกี่ยวข้อง, สัมพันธ์กัน (adj.)" },
  { vocab: "Endeavor", result: "ความพยายาม (n.), พยายาม (v.)" },
  {
    vocab: "Dismay",
    result: "ความตกใจ, ความผิดหวัง (n.), ทำให้ตกใจ, ทำให้ผิดหวัง (v.)",
  },
  { vocab: "Advocate", result: "ผู้สนับสนุน (n.), สนับสนุน (v.)" },
  { vocab: "Retain", result: "เก็บไว้, รักษาไว้ (v.)" },
  {
    vocab: "Contrary",
    result: "ตรงกันข้าม (adj.), สิ่งที่ตรงกันข้าม (n.)",
  },
  { vocab: "Keen", result: "กระตือรือร้น, แหลมคม (adj.)" },
  {
    vocab: "Elaborate",
    result: "ละเอียด, ซับซ้อน (adj.), อธิบายอย่างละเอียด (v.)",
  },
  { vocab: "Modest", result: "ถ่อมตัว, พอประมาณ (adj.)" },
  { vocab: "Liberal", result: "เสรีนิยม, ใจกว้าง (adj.)" },
  { vocab: "Thrifty", result: "ประหยัด, มัธยัสถ์ (adj.)" },
  { vocab: "Privileged", result: "มีสิทธิพิเศษ, มีอภิสิทธิ์ (adj.)" },
  { vocab: "Derive", result: "ได้มา, สืบทอดมา (v.)" },
  { vocab: "Conceal", result: "ปกปิด, ซ่อนเร้น (v.)" },
  { vocab: "Disguise", result: "ปลอมแปลง, ปิดบัง (v.)" },
  { vocab: "Coerce", result: "บังคับ, ขู่เข็ญ (v.)" },
  { vocab: "Plausible", result: "เป็นไปได้, น่าเชื่อถือ (adj.)" },
  { vocab: "Absurd", result: "ไร้สาระ, เหลวไหล (adj.)" },
  { vocab: "Peculiar", result: "แปลกประหลาด, พิเศษ (adj.)" },
  { vocab: "Tedious", result: "น่าเบื่อ, ยืดยาว (adj.)" },
  { vocab: "Diminish", result: "ลดลง, ทำให้ลดลง (v.)" },
  { vocab: "Intensify", result: "ทำให้รุนแรงขึ้น, เพิ่มขึ้น (v.)" },
  { vocab: "Discriminate", result: "แบ่งแยก, เลือกปฏิบัติ (v.)" },
  { vocab: "Profound", result: "ลึกซึ้ง, ยิ่งใหญ่ (adj.)" },
  { vocab: "Vocation", result: "อาชีพ, งานที่ถนัด (n.)" },
  { vocab: "Profession", result: "อาชีพ, วิชาชีพ (n.)" },
  { vocab: "Prestige", result: "เกียรติยศ, ศักดิ์ศรี (n.)" },
  { vocab: "Dignity", result: "ศักดิ์ศรี, ความมีเกียรติ (n.)" },
  { vocab: "Intervene", result: "แทรกแซง, เข้าไปยุ่งเกี่ยว (v.)" },
  { vocab: "Refrain", result: "ละเว้น, งดเว้น (v.)" },
  { vocab: "Obstinate", result: "ดื้อรั้น, หัวแข็ง (adj.)" },
  { vocab: "Stubborn", result: "ดื้อดึง, หัวแข็ง (adj.)" },
  { vocab: "Ample", result: "มากพอ, เหลือเฟือ (adj.)" },
  { vocab: "Harsh", result: "รุนแรง, หยาบคาย (adj.)" },
  { vocab: "Vigorous", result: "กระฉับกระเฉง, แข็งแรง (adj.)" },
  { vocab: "Delicate", result: "บอบบาง, อ่อนไหว (adj.)" },
  { vocab: "Adverse", result: "เป็นผลร้าย, ตรงกันข้าม (adj.)" },
  { vocab: "Bestow", result: "มอบให้, ให้เป็นของขวัญ (v.)" },
  { vocab: "Exploit", result: "ใช้ประโยชน์, เอาเปรียบ (v.)" },
  { vocab: "Enrich", result: "ทำให้มั่งคั่ง, ทำให้สมบูรณ์ (v.)" },
  { vocab: "Amend", result: "แก้ไข, ปรับปรุง (v.)" },
];

const index = Math.floor(Math.random() * vocabList.length);
console.log(vocabList[index]);
